#fixtures:
#  stdlib: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
#  firewall: "git@github.com:puppetlabs/puppetlabs-firewall.git"
#  lvm: "git@github.com:puppetlabs/puppetlabs-lvm.git"
#  xinetd: "git@github.com:puppetlabs/puppetlabs-xinetd.git"
#  keepalived: "git@github.com:arioch/puppet-keepalived.git"
#  concat: "git@github.com:puppetlabs/puppetlabs-concat.git"

fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "5.3.0"
    cron_core:
      repo: 'puppetlabs/cron_core'
      ref: '1.0.3'
    firewall:
      repo: "puppetlabs/firewall"
      ref: "2.2.0"
    keepalived:
      repo: "puppet/keepalived"
      ref: "2.2.0"
    lvm:
      repo: "puppetlabs/lvm"
      ref: "1.2.0"
    mount_core:
      repo: "puppetlabs/mount_core"
      ref: "1.0.3"
    nfs:
      repo: "derdanne/nfs"
      ref: "2.1.4"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.0.0"
      #flags: "--module_repository https://my_repo.com"
    xinetd:
      repo: "puppetlabs/xinetd"
      ref: "3.3.0"
    #repositories:
    #  firewall:
    #    repo: "git://github.com/puppetlabs/puppetlabs-firewall"
    #    ref: "2.6.0"
    #    flags: "--verbose"

