#fixtures:
#  stdlib: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
#  firewall: "git@github.com:puppetlabs/puppetlabs-firewall.git"
#  lvm: "git@github.com:puppetlabs/puppetlabs-lvm.git"
#  xinetd: "git@github.com:puppetlabs/puppetlabs-xinetd.git"
#  keepalived: "git@github.com:arioch/puppet-keepalived.git"
#  concat: "git@github.com:puppetlabs/puppetlabs-concat.git"

fixtures:
  forge_modules:
    nfs:
      repo: "derdanne-nfs"
      ref: "2.0.10"
    concat:
      repo: "puppetlabs-concat"
      ref: "4.2.1"
    xinetd:
      repo: "puppetlabs/xinetd"
      ref: "3.0.0"
    keepalived:
      repo: "arioch/keepalived"
      ref: "1.2.5"
    cron_core:
      repo: 'puppetlabs/cron_core'
      ref: '1.0.0'
    firewall:
      repo: "puppetlabs/firewall"
      ref: "1.9.0"
    lvm:
      repo: "puppetlabs/lvm"
      ref: "0.9.0"
    mount_core:
      repo: "puppetlabs/mount_core"
      ref: "1.0.2"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.24.0"
      #flags: "--module_repository https://my_repo.com"
    #repositories:
    #  firewall:
    #    repo: "git://github.com/puppetlabs/puppetlabs-firewall"
    #    ref: "2.6.0"
    #    flags: "--verbose"

